export const suffixes = [
    '',            // Empty string for no suffix
    'K',           // Thousand
    'Mil',         // Million
    'Bil',         // Billion
    'Tri',         // Trillion
    'Quad',        // Quadrillion
    'Quint',       // Quintillion
    'Sext',        // Sextillion
    'Sept',        // Septillion
    'Oct',         // Octillion       
    'Non',         // Nonillion
    'Dec',         // Decillion
    'Undec',       // Undecillion
    'Duodec',      // Duodecillion
    'Tredec',      // Tredecillion
    'Quattuordec', // Quattuordecillion
    'Quindec',     // Quindecillion
    'Sexdec',      // Sexdecillion
    'Septendec',   // Septendecillion
    'Octodec',     // Octodecillion
    'Novemdec',    // Novemdecillion
    'Vigint',      // Vigintillion
    'Unvigint',    // Unvigintillion
    'Duovigint',   // Duovigintillion
    'Trevigint',   // Trevigintillion
    'Quattuorvigint', // Quattuorvigintillion
    'Quinvigint',  // Quinvigintillion
    'Sexvigint',   // Sexvigintillion
    'Septenvigint', // Septenvigintillion
    'Octovigint',  // Octovigintillion
    'Novemvigint', // Novemvigintillion
    'Trigint',     // Trigintillion
    'Untrigint',   // Untrigintillion
    'Duotrigint',  // Duotrigintillion
    'Trestrigint', // Trestrigintillion
    'Quattuortrigint', // Quattuortrigintillion
    'Quintrigint', // Quintrigintillion
    'Sextrigint',  // Sextrigintillion
    'Septentrigint', // Septentrigintillion
    'Octotrigint', // Octotrigintillion
    'Novemtrigint', // Novemtrigintillion
    'Quadragint',  // Quadragintillion
    'Unquadragint', // Unquadragintillion
    'Duoquadragint', // Duoquadragintillion
    'Tresquadragint', // Tresquadragintillion
    'Quattuorquadragint', // Quattuorquadragintillion
    'Quinquadragint', // Quinquadragintillion
    'Sexquadragint', // Sexquadragintillion
    'Septenquadragint', // Septenquadragintillion
    'Octoquadragint', // Octoquadragintillion
    'Novemquadragint', // Novemquadragintillion
    'Quinquagint',  // Quinquagintillion
    'Unquinquagint', // Unquinquagintillion
    'Duoquinquagint', // Duoquinquagintillion
    'Trequinquagint', // Trequinquagintillion
    'Quattuorquinquagint', // Quattuorquinquagintillion
    'Quinquinquagint', // Quinquinquagintillion
    'Sexquinquagint', // Sexquinquagintillion
    'Septenquinquagint', // Septenquinquagintillion
    'Octoquinquagint', // Octoquinquagintillion
    'Novemquinquagint', // Novemquinquagintillion
    'Sexagint',     // Sexagintillion
];
